import Fileds from "./Fileds";

const Heading = {
  Agents: {
    key: "Agents",
    heading: "Agents",
    cols: "grid-cols-4",
    fields: [Fileds.Name, Fileds.Type, Fileds.Commission, Fileds.Iscommission],
    Button: true,
    button: "Add Agents ",
    size: "w-[100px]",
  },
  Clients: {
    key: "Clients",
    heading: "Clients",
    cols: "grid-cols-2",
    fields: [Fileds.Name, Fileds.Type],
    Button: true,
    button: "Add Clients ",
    size: "w-[100px]",
  },
  Loyers: {
    key: "Loyers",
    heading: "Loyers",
    cols: "grid-cols-2",
    fields: [Fileds.Name, Fileds.Type],
    Button: true,
    size: "w-[100px]",
    button: "Add Loyers ",
  },
  Office: {
    key: "Office",
    heading: "OFFICE",
    cols: "grid-cols-3",
    fields: [Fileds.Name, Fileds.Address, Fileds.Code],
    size: "w-[100px]",
    Button: false,
  },
  InvoicingProfile: {
    key: "InvoicingProfile",
    heading: "INVOICING PROFILE",
    cols: "grid-cols-8",
    fields: [
      Fileds.PRODUCT,
      Fileds.VALUE,
      Fileds.Per,
      Fileds.TRAN,
      Fileds.VAR,
      Fileds.MIN,
      Fileds.MAX,
      Fileds.Type,
    ],
    size: "w-[320px]",
  },
  RecurringPayments: {
    key: "RecurringPayments",
    heading: "RECURRING PAYMENTS",
    cols: "grid-cols-6",
    fields: [
      Fileds.Name,
      Fileds.RE_STATUS,
      Fileds.STATUS,
      Fileds.Amount,
      Fileds.DATE,
      Fileds.Applied,
    ],
    size: "w-[400px]",
  },
  INVOICESAGENT: {
    key: "INVOICESAGENT",
    heading: "INVOICES AGENT",
    cols: "grid-cols-7",
    fields: [
      Fileds.Number,
      Fileds.DATE,
      Fileds.Name,
      Fileds.BALANCE,
      Fileds.BALANCE_To,
      Fileds.STATUS,
      Fileds.SYNC,
    ],
    size: "w-[260px]",
  },
  INVOICESAGENTTRAN: {
    key: "INVOICESAGENTTRAN",
    heading: "INVOICE TRANSACTION",
    cols: "grid-cols-7",
    fields: [
      Fileds.Name,
      Fileds.Number,
      Fileds.DATE,
      Fileds.BALANCE,
      Fileds.BALANCE_To,
      Fileds.STATUS,
      Fileds.SYNC,
    ],
    size: "w-[400px]",
  },
  STATEMENT: {
    key: "STATEMENT",
    heading: "STATEMENT",
    cols: "grid-cols-7",
    fields: [
      Fileds.RECEIPT,
      Fileds.Name,
      Fileds.DATE,
      Fileds.BALANCE,
      Fileds.BALANCE_To,
      Fileds.STATUS,
      Fileds.SYNC,
    ],
    Button: true,
    size: "w-[320px]",
  },
  INVOICES: {
    key: "INVOICES",
    heading: "INVOICES",
    cols: "grid-cols-7",
    Button: true,
    fields: [
      Fileds.RECEIPT,
      Fileds.Name,
      Fileds.DATE,
      Fileds.BALANCE,
      Fileds.BALANCE_To,
      Fileds.STATUS,
      Fileds.SYNC,
    ],
    size: "w-[400px]",
  },
  SHOWINGREQUEST: {
    key: "SHOWINGREQUEST",
    heading: "SHOWING REQUEST",
    cols: "grid-cols-6",
    fields: [
      Fileds.Address,
      Fileds.Agents,
      Fileds.BROKERAGE,
      Fileds.START,
      Fileds.END,
      Fileds.STATUS,
    ],
    size: "w-[400px]",
  },
  TRUST_DEPOSITS: {
    key: "TRUST_DEPOSITS",
    heading: "TRUST DEPOSITS",
    cols: "grid-cols-6",
    fields: [
      Fileds.RECEIPT,
      Fileds.Name,
      Fileds.DATE,
      Fileds.REMAINING,
      Fileds.STATUS,
      Fileds.SYNC,
    ],
    size: "w-[400px]",
  },
  TRUST_LEDGER: {
    key: "TRUST_LEDGER",
    heading: "TRUST LEDGER",
    cols: "grid-cols-5",

    fields: [
      Fileds.Name,
      Fileds.DATE,
      Fileds.RECEIPT,
      Fileds.DEPOSIT,
      Fileds.WITHDRAWAL,
    ],
    size: "w-[400px]",
  },
  LISTING: {
    key: "LISTING",
    heading: "LISTING",
    cols: "grid-cols-7",
    fields: [
      Fileds.MLS,
      Fileds.PRICE,
      Fileds.CREATED,
      Fileds.REGISTERED,
      Fileds.EXPIRE,
      Fileds.Type,
      Fileds.STATUS,
    ],
    Button: false,
    size: "w-[100px]",
  },
  OFFER: {
    key: "OFFER",
    heading: "OFFER",
    cols: "grid-cols-7",
    fields: [
      Fileds.ID,
      Fileds.PRICE,
      Fileds.DEPOSIT,
      Fileds.RELEASEDATE,
      Fileds.STATUS,
      Fileds.CONDITION,
      Fileds.POSITION,
    ],
    Button: false,
    size: "w-[100px]",
  },
  TRANSACTION: {
    key: "TRANSACTION",
    heading: "TRANSACTION",
    cols: "grid-cols-7",
    fields: [
      Fileds.Number,
      Fileds.PRICE,
      Fileds.OFFERDATE,
      Fileds.CREATED,
      Fileds.CLOSING,
      Fileds.Type,
      Fileds.STATUS,
    ],
    size: "w-[200px]",
  },
};

export default Heading;
